"""nwupdater — updater NumWorks headless, indépendant et non officiel.

⚠️ Projet de hobby, SANS lien avec NumWorks SAS. Voir ``DISCLAIMER`` ci-dessous et le
fichier ``DISCLAIMER.md`` à la racine.
"""

# Version is derived from the git tag by setuptools-scm and baked into ``_version.py`` at
# build/install time (see ``[tool.setuptools_scm]`` in pyproject.toml). Running from a bare
# source checkout that was never built (e.g. PYTHONPATH=src), ``_version.py`` is absent: fall
# back to a sentinel. diagnose._version() prefers a live ``git describe`` in that case anyway.
try:
    from ._version import __version__  # generated by setuptools-scm, git-ignored
except ImportError:  # pragma: no cover - only on an unbuilt source tree
    __version__ = "0.0.0+unknown"


def ensure_suffix(name: str, suffix: str) -> str:
    """Return ``name`` with ``suffix`` appended unless it is already there (e.g. ``"a" ->
    "a.py"``, ``"a.py" -> "a.py"``). Shared by the script (``.py``) and app (``.nwa``) paths so the
    filename-normalisation idiom lives in one place."""
    return name if name.endswith(suffix) else name + suffix


# ----------------------------------------------------------------------------------------
# Avertissement affiché un peu partout (CLI, UI web, docs). Le flashage d'une calculatrice
# est une opération à risque : ce projet décline toute responsabilité.
# ----------------------------------------------------------------------------------------
DISCLAIMER_SHORT = (
    "Projet indépendant de hobby — NON officiel, sans lien avec NumWorks SAS. "
    "Fourni SANS AUCUNE GARANTIE : mettre à jour ou flasher une calculatrice peut "
    "l'endommager, effacer vos données ou la rendre inutilisable (« brick »). "
    "Utilisation à vos seuls risques ; mineurs sous supervision d'un adulte."
)

DISCLAIMER = (
    "AVERTISSEMENT / DISCLAIMER\n"
    "\n"
    "nwupdater est un projet INDÉPENDANT et de HOBBY. Ce n'est PAS une application "
    "officielle NumWorks et il n'a AUCUN lien avec NumWorks SAS.\n"
    "\n"
    "Le logiciel est fourni « EN L'ÉTAT », SANS AUCUNE GARANTIE d'aucune sorte. Mettre à "
    "jour, flasher ou modifier le firmware d'une calculatrice est une opération À RISQUE "
    "qui peut l'endommager, effacer vos données, invalider la garantie constructeur ou "
    "rendre l'appareil définitivement inutilisable (« brick »).\n"
    "\n"
    "Vous utilisez cet outil À VOS SEULS RISQUES. Les auteurs et contributeurs déclinent "
    "toute responsabilité pour tout dommage matériel, perte de données ou tout autre "
    "préjudice résultant de son utilisation.\n"
    "\n"
    "Les calculatrices étant des outils scolaires, toute opération de flashage réalisée par "
    "un mineur doit se faire sous la supervision d'un adulte.\n"
    "\n"
    "« NumWorks » et « Epsilon » sont des marques de leurs détenteurs respectifs, cités "
    "à des fins d'interopérabilité uniquement."
)
