#!/usr/bin/env python3
"""Compile the clean-room EADK runtime (``src/nwupdater/formats/eadk_runtime.s``) and embed the
resulting ARM ``ET_REL`` object as a base64 blob in ``src/nwupdater/formats/_eadk_runtime.py``.

Run this whenever ``eadk_runtime.s`` changes. It needs a cross-``clang`` (any recent LLVM clang
targets ``arm-none-eabi``); the SHIPPED tool does NOT — end users get the pre-built blob and the
pure-Python linker, no toolchain, no Node. The blob is OUR artifact (MIT), built from OUR source.

    python scripts/build_eadk_runtime.py
"""

from __future__ import annotations

import base64
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC_S = ROOT / "src" / "nwupdater" / "formats" / "eadk_runtime.s"
OUT_PY = ROOT / "src" / "nwupdater" / "formats" / "_eadk_runtime.py"

CLANG_FLAGS = [
    "--target=arm-none-eabi",
    "-mthumb",
    "-mcpu=cortex-m7",
    "-mfloat-abi=hard",
    "-mfpu=fpv5-sp-d16",
]


def main() -> int:
    if not SRC_S.exists():
        print(f"missing {SRC_S}", file=sys.stderr)
        return 1
    with tempfile.TemporaryDirectory() as td:
        obj = Path(td) / "eadk_runtime.o"
        cmd = ["clang", *CLANG_FLAGS, "-c", str(SRC_S), "-o", str(obj)]
        proc = subprocess.run(cmd, capture_output=True, text=True, check=False)
        if proc.returncode != 0:
            print(proc.stderr, file=sys.stderr)
            return proc.returncode
        blob = obj.read_bytes()
    b64 = base64.b64encode(blob).decode("ascii")
    wrapped = "\n".join(f'    "{b64[i : i + 96]}"' for i in range(0, len(b64), 96))
    OUT_PY.write_text(
        '"""Generated by scripts/build_eadk_runtime.py — do NOT edit by hand.\n\n'
        "The base64 below is our clean-room EADK runtime (crt0 + eadk_* svc stubs + newlib stubs),\n"
        "compiled from ``eadk_runtime.s`` into an ARM ``ET_REL`` object. Shipping it as data lets the\n"
        "pure-Python linker run with no toolchain and no Node. MIT, our own code — see the .s source.\n"
        '"""\n\n'
        "import base64\n\n"
        "_B64 = (\n" + wrapped + "\n)\n\n"
        "RUNTIME_OBJECT: bytes = base64.b64decode(_B64)\n",
        encoding="utf-8",
    )
    print(f"wrote {OUT_PY} ({len(blob)} B object -> {len(b64)} b64 chars)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
